services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rlv
      POSTGRES_DATABASE: rlv
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: npm run dev
    volumes:
      - .:/app:rw
    ports:
      - "3000:3000"
    depends_on:
      - db
